version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lab8
    environment:
      # Sets the password for the 'root' user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customer_management
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci